spring:
  datasource:
    url: jdbc:mysql://localhost:3306/finance_news
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

ksd:
  api:
    key: ${KSD_API_KEY:LnXWoThk2rbcO4LlfudvXpEZMxJu7Pl4YPlZBaHlf5UwsXilLsP6v/6vpNjnveyxuIQi5PFHMZKHlK88I6d4LQ==}
    url: http://api.seibro.or.kr/openapi/service/FnTermSvc/getFinancialTermMeaning
    timeout: 5000

logging:
  level:
    Project.Finacne_News: DEBUG
    org.hibernate.SQL: DEBUG
